# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userp', '0002_auto_20160820_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.URLField(default='https://lh4.googleusercontent.com/-fEed_duHZ0E/VpPTyoNjdGI/AAAAAAAADNE/by47Xe84u2g4_dzc9ixG_V7gKF5Ep_C6gCL0B/w854-h852-no/maxresdefault.jpg'),
            preserve_default=False,
        ),
    ]
